name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore packages
      run: nuget restore youtube-play.sln
    - name: MSBuild project
      run: msbuild youtube-play.sln /p:Configuration=Release
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: youtube-play
        path: youtube-play/bin/Release/youtube-play.exe
